--------------------------------------------------------
--  DDL for Table SERVICE_GROUP_CONFIG
--------------------------------------------------------

  CREATE TABLE "SERVICE_GROUP_CONFIG" 
   (	"ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(50), 
	"SOURCE_SYSTEM_ID" NUMBER, 
	"TARGET_SYSTEM_ID" NUMBER, 
	"SCHEDULE_CRON" VARCHAR2(20), 
	"LAST_EXECUTION" TIMESTAMP (6), 
	"IS_RUNNING" CHAR(1) DEFAULT 'N', 
	"EXECUTION_MODE" VARCHAR2(20) DEFAULT 'SCHEDULED', 
	"IS_ACTIVE" CHAR(1) DEFAULT 'N', 
	"ERROR_THRESHOLD" NUMBER(3,0) DEFAULT 3, 
	"ERROR_COUNT" NUMBER(3,0) DEFAULT 0
   ) ;

   COMMENT ON TABLE "SERVICE_GROUP_CONFIG"  IS 'Groups of ETL processes between source and target systems';
/
REM INSERTING into SERVICE_GROUP_CONFIG
SET DEFINE OFF;
Insert into SERVICE_GROUP_CONFIG (ID,GROUP_NAME,SOURCE_SYSTEM_ID,TARGET_SYSTEM_ID,SCHEDULE_CRON,LAST_EXECUTION,IS_RUNNING,EXECUTION_MODE,IS_ACTIVE,ERROR_THRESHOLD,ERROR_COUNT) values (2,'REALTIME_STREAMS',4,11,null,to_timestamp('01-04-25 11:22:28.000000000 AM','DD-MM-RR HH12:MI:SS.FF AM'),'N','CONTINUOUS','Y',999,0);
Insert into SERVICE_GROUP_CONFIG (ID,GROUP_NAME,SOURCE_SYSTEM_ID,TARGET_SYSTEM_ID,SCHEDULE_CRON,LAST_EXECUTION,IS_RUNNING,EXECUTION_MODE,IS_ACTIVE,ERROR_THRESHOLD,ERROR_COUNT) values (3,'HR_TO_HR',11,11,'* * * * *',to_timestamp('01-04-25 11:22:01.000000000 AM','DD-MM-RR HH12:MI:SS.FF AM'),'N','SCHEDULED','Y',3,0);
Insert into SERVICE_GROUP_CONFIG (ID,GROUP_NAME,SOURCE_SYSTEM_ID,TARGET_SYSTEM_ID,SCHEDULE_CRON,LAST_EXECUTION,IS_RUNNING,EXECUTION_MODE,IS_ACTIVE,ERROR_THRESHOLD,ERROR_COUNT) values (21,'MYSQL_TO_HR',2,11,'* * * * *',to_timestamp('01-04-25 11:22:01.000000000 AM','DD-MM-RR HH12:MI:SS.FF AM'),'N','SCHEDULED','Y',3,0);
--------------------------------------------------------
--  DDL for Index SYS_C0010708
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010708" ON "SERVICE_GROUP_CONFIG" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C0010709
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010709" ON "SERVICE_GROUP_CONFIG" ("GROUP_NAME") 
  ;
/
--------------------------------------------------------
--  Constraints for Table SERVICE_GROUP_CONFIG
--------------------------------------------------------

  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD CHECK (execution_mode IN ('SCHEDULED', 'CONTINUOUS')) ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD UNIQUE ("GROUP_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD CHECK (IS_RUNNING IN ('Y','N')) ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD CHECK (is_active IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" MODIFY ("TARGET_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SERVICE_GROUP_CONFIG" MODIFY ("SOURCE_SYSTEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SERVICE_GROUP_CONFIG" MODIFY ("GROUP_NAME" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_GROUP_CONFIG
--------------------------------------------------------

  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD FOREIGN KEY ("SOURCE_SYSTEM_ID")
	  REFERENCES "SYSTEM_CONFIG" ("ID") ENABLE;
  ALTER TABLE "SERVICE_GROUP_CONFIG" ADD FOREIGN KEY ("TARGET_SYSTEM_ID")
	  REFERENCES "SYSTEM_CONFIG" ("ID") ENABLE;
/
--------------------------------------------------------
--  DDL for Trigger SERVICE_GROUP_CONFIG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SERVICE_GROUP_CONFIG_TRG" 
BEFORE INSERT ON service_group_config
FOR EACH ROW
BEGIN
    :new.ID := service_group_seq.nextval;
END;
/
ALTER TRIGGER "SERVICE_GROUP_CONFIG_TRG" ENABLE;
/



--------------------------------------------------------
--  DDL for Table SYSTEM_CONFIG
--------------------------------------------------------

  CREATE TABLE "SYSTEM_CONFIG" 
   (	"ID" NUMBER, 
	"SYSTEM_NAME" VARCHAR2(50), 
	"SYSTEM_TYPE" VARCHAR2(20), 
	"CONNECTION_CONFIG" CLOB, 
	"IS_ACTIVE" CHAR(1) DEFAULT 'Y', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

   COMMENT ON COLUMN "SYSTEM_CONFIG"."CONNECTION_CONFIG" IS 'JSON formatted connection parameters';
   COMMENT ON TABLE "SYSTEM_CONFIG"  IS 'Stores connection details for all source and target systems';
/
REM INSERTING into SYSTEM_CONFIG
SET DEFINE OFF;
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (1,'ORACLE_DW','ORACLE','Y',to_timestamp('24-03-25 06:04:06.868000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (2,'MYSQL_ERP','MYSQL','Y',to_timestamp('24-03-25 06:04:06.882000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (3,'SALES_API','API','Y',to_timestamp('24-03-25 06:04:06.887000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (4,'LOG_STREAM','KAFKA','Y',to_timestamp('24-03-25 06:04:06.892000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (5,'ORACLE_ERP','ORACLE','Y',to_timestamp('24-03-25 06:04:18.554000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
Insert into SYSTEM_CONFIG (ID,SYSTEM_NAME,SYSTEM_TYPE,IS_ACTIVE,CREATED_AT) values (11,'ORACLE_HR','ORACLE','Y',to_timestamp('24-03-25 06:13:11.908000000 PM','DD-MM-RR HH12:MI:SS.FF AM'));
--------------------------------------------------------
--  DDL for Index SYS_C0010701
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010701" ON "SYSTEM_CONFIG" ("ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SYS_C0010702
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010702" ON "SYSTEM_CONFIG" ("SYSTEM_NAME") 
  ;
/
--------------------------------------------------------
--  Constraints for Table SYSTEM_CONFIG
--------------------------------------------------------

  ALTER TABLE "SYSTEM_CONFIG" ADD UNIQUE ("SYSTEM_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SYSTEM_CONFIG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SYSTEM_CONFIG" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "SYSTEM_CONFIG" MODIFY ("CONNECTION_CONFIG" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM_CONFIG" MODIFY ("SYSTEM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM_CONFIG" MODIFY ("SYSTEM_NAME" NOT NULL ENABLE);
/
--------------------------------------------------------
--  DDL for Trigger SYSTEM_CONFIG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SYSTEM_CONFIG_TRG" 
BEFORE INSERT ON SYSTEM_CONFIG
FOR EACH ROW
BEGIN
    :new.ID := system_config_seq.nextval;
END;
/
ALTER TRIGGER "SYSTEM_CONFIG_TRG" ENABLE;
/


--------------------------------------------------------
--  DDL for Table SERVICE_DETAIL_CONFIG
--------------------------------------------------------

  CREATE TABLE "SERVICE_DETAIL_CONFIG" 
   (	"ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"SOURCE_TYPE" VARCHAR2(20), 
	"SOURCE_DATA_TYPE" VARCHAR2(10), 
	"EXTRACTION_QUERY" CLOB, 
	"DESTINATION_TABLE" VARCHAR2(30), 
	"TARGET_TRUNCATE" CHAR(1) DEFAULT 'N', 
	"TRIM_COL_LIST" VARCHAR2(4000), 
	"PROCESS_ORDER" NUMBER, 
	"SERVICE_DETAIL_NAME" VARCHAR2(100)
   ) ;

   COMMENT ON COLUMN "SERVICE_DETAIL_CONFIG"."TRIM_COL_LIST" IS 'JSON array of columns to trim whitespace';
/
REM INSERTING into SERVICE_DETAIL_CONFIG
SET DEFINE OFF;
Insert into SERVICE_DETAIL_CONFIG (ID,GROUP_ID,SOURCE_TYPE,SOURCE_DATA_TYPE,DESTINATION_TABLE,TARGET_TRUNCATE,TRIM_COL_LIST,PROCESS_ORDER,SERVICE_DETAIL_NAME) values (3,2,'KAFKA','JSON','TEMP_KAFKA','N',null,1,'LOCAL_KAFKA_ETLTEST1');
Insert into SERVICE_DETAIL_CONFIG (ID,GROUP_ID,SOURCE_TYPE,SOURCE_DATA_TYPE,DESTINATION_TABLE,TARGET_TRUNCATE,TRIM_COL_LIST,PROCESS_ORDER,SERVICE_DETAIL_NAME) values (9,3,'ORACLE','TABLE','temp_emp','Y','[{"last_name"}]',1,'TEMP_EMP');
Insert into SERVICE_DETAIL_CONFIG (ID,GROUP_ID,SOURCE_TYPE,SOURCE_DATA_TYPE,DESTINATION_TABLE,TARGET_TRUNCATE,TRIM_COL_LIST,PROCESS_ORDER,SERVICE_DETAIL_NAME) values (10,3,'ORACLE','TABLE','temp_dept','Y','[{"department_name"}]',2,'TEMP_DEPT');
Insert into SERVICE_DETAIL_CONFIG (ID,GROUP_ID,SOURCE_TYPE,SOURCE_DATA_TYPE,DESTINATION_TABLE,TARGET_TRUNCATE,TRIM_COL_LIST,PROCESS_ORDER,SERVICE_DETAIL_NAME) values (21,21,'MYSQL','TABLE','temp_actor','Y','[{"first_name"}]',1,'TEMP_ACTOR');
--------------------------------------------------------
--  DDL for Index SYS_C0010719
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010719" ON "SERVICE_DETAIL_CONFIG" ("ID") 
  ;
/
--------------------------------------------------------
--  Constraints for Table SERVICE_DETAIL_CONFIG
--------------------------------------------------------

  ALTER TABLE "SERVICE_DETAIL_CONFIG" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICE_DETAIL_CONFIG" ADD CHECK (TARGET_TRUNCATE IN ('Y','N')) ENABLE;
  ALTER TABLE "SERVICE_DETAIL_CONFIG" MODIFY ("PROCESS_ORDER" NOT NULL ENABLE);
  ALTER TABLE "SERVICE_DETAIL_CONFIG" MODIFY ("DESTINATION_TABLE" NOT NULL ENABLE);
  ALTER TABLE "SERVICE_DETAIL_CONFIG" MODIFY ("SOURCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SERVICE_DETAIL_CONFIG" MODIFY ("GROUP_ID" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Ref Constraints for Table SERVICE_DETAIL_CONFIG
--------------------------------------------------------

  ALTER TABLE "SERVICE_DETAIL_CONFIG" ADD FOREIGN KEY ("GROUP_ID")
	  REFERENCES "SERVICE_GROUP_CONFIG" ("ID") ENABLE;
/
--------------------------------------------------------
--  DDL for Trigger SERVICE_DETAIL_CONFIG_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SERVICE_DETAIL_CONFIG_TRG" 
BEFORE INSERT ON service_detail_config
FOR EACH ROW
BEGIN
    :new.ID := service_detail_seq.nextval;
END;
/
ALTER TRIGGER "SERVICE_DETAIL_CONFIG_TRG" ENABLE;
/
