-- Sequences for all tables
CREATE SEQUENCE system_config_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE service_group_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE service_detail_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE column_mapping_seq START WITH 1 INCREMENT BY 1;

-- System Configuration Table
CREATE TABLE SYSTEM_CONFIG (
    ID NUMBER PRIMARY KEY,
    SYSTEM_NAME VARCHAR2(50) NOT NULL UNIQUE,
    SYSTEM_TYPE VARCHAR2(20) CHECK (SYSTEM_TYPE IN ('ORACLE','JDBC','API','KAFKA')) NOT NULL,
    CONNECTION_CONFIG CLOB NOT NULL CHECK (CONNECTION_CONFIG IS JSON),
    IS_ACTIVE CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

COMMENT ON TABLE SYSTEM_CONFIG IS 'Stores connection details for all source and target systems';
COMMENT ON COLUMN SYSTEM_CONFIG.CONNECTION_CONFIG IS 'JSON formatted connection parameters';

-- Service Group Configuration
CREATE TABLE SERVICE_GROUP_CONFIG (
    ID NUMBER PRIMARY KEY,
    GROUP_NAME VARCHAR2(50) NOT NULL UNIQUE,
    SOURCE_SYSTEM_ID NUMBER NOT NULL REFERENCES SYSTEM_CONFIG(ID),
    TARGET_SYSTEM_ID NUMBER NOT NULL REFERENCES SYSTEM_CONFIG(ID),
    SCHEDULE_CRON VARCHAR2(20) NOT NULL,
    LAST_EXECUTION TIMESTAMP,
    IS_RUNNING CHAR(1) DEFAULT 'N' CHECK (IS_RUNNING IN ('Y','N'))
);

COMMENT ON TABLE SERVICE_GROUP_CONFIG IS 'Groups of ETL processes between source and target systems';

-- Service Detail Configuration
CREATE TABLE SERVICE_DETAIL_CONFIG (
    ID NUMBER PRIMARY KEY,
    GROUP_ID NUMBER NOT NULL REFERENCES SERVICE_GROUP_CONFIG(ID),
    SOURCE_TYPE VARCHAR2(20) CHECK (SOURCE_TYPE IN ('DATABASE','API','KAFKA')) NOT NULL,
    SOURCE_DATA_TYPE VARCHAR2(10) CHECK (SOURCE_DATA_TYPE IN ('TABLE','JSON','XML','CSV')),
    EXTRACTION_QUERY CLOB,
    DESTINATION_TABLE VARCHAR2(30) NOT NULL,
    TARGET_TRUNCATE CHAR(1) DEFAULT 'N' CHECK (TARGET_TRUNCATE IN ('Y','N')),
    TRIM_COL_LIST VARCHAR2(4000),
    PROCESS_ORDER NUMBER NOT NULL
);

COMMENT ON COLUMN SERVICE_DETAIL_CONFIG.TRIM_COL_LIST IS 'JSON array of columns to trim whitespace';

-- Column Mapping Table
CREATE TABLE SERVICE_COLUMN_MAPPING (
    ID NUMBER PRIMARY KEY,
    SERVICE_DETAIL_ID NUMBER NOT NULL REFERENCES SERVICE_DETAIL_CONFIG(ID),
    SOURCE_PATH VARCHAR2(400) NOT NULL,
    DESTINATION_COLUMN VARCHAR2(30) NOT NULL,
    DATA_TYPE VARCHAR2(20),
    TRANSFORMATION VARCHAR2(50),
    PROCESS_ORDER NUMBER NOT NULL
);

-- Triggers for auto-increment
CREATE OR REPLACE TRIGGER system_config_trg
BEFORE INSERT ON SYSTEM_CONFIG
FOR EACH ROW
BEGIN
    :new.ID := system_config_seq.nextval;
END;
/

-- Similar triggers for other tables...

-- Sample Data for All Source Types

-- System Configurations
INSERT INTO SYSTEM_CONFIG (SYSTEM_NAME, SYSTEM_TYPE, CONNECTION_CONFIG) VALUES (
    'ORACLE_DW',
    'ORACLE',
    '{
        "host": "dw-host",
        "port": 1521,
        "service_name": "DWPROD",
        "user": "etl_user",
        "password": "etl_pass",
        "conn_timeout": 30
    }'
);

INSERT INTO SYSTEM_CONFIG (SYSTEM_NAME, SYSTEM_TYPE, CONNECTION_CONFIG) VALUES (
    'MYSQL_ERP',
    'JDBC',
    '{
        "jdbc_class": "com.mysql.cj.jdbc.Driver",
        "jdbc_url": "jdbc:mysql://erp-db:3306/erp",
        "user": "erp_user",
        "password": "erp_pass",
        "jars": "/jdbc/mysql-connector.jar"
    }'
);

INSERT INTO SYSTEM_CONFIG (SYSTEM_NAME, SYSTEM_TYPE, CONNECTION_CONFIG) VALUES (
    'SALES_API',
    'API',
    '{
        "base_url": "https://api.sales.com/v2",
        "auth_type": "OAUTH2",
        "client_id": "api_client",
        "client_secret": "secret123",
        "default_headers": {"Accept": "application/json"}
    }'
);

INSERT INTO SYSTEM_CONFIG (SYSTEM_NAME, SYSTEM_TYPE, CONNECTION_CONFIG) VALUES (
    'LOG_STREAM',
    'KAFKA',
    '{
        "bootstrap_servers": "kafka1:9092,kafka2:9092",
        "topic": "server-logs",
        "group_id": "etl-group",
        "auto_offset_reset": "earliest"
    }'
);



-- Service Groups
INSERT INTO SERVICE_GROUP_CONFIG (ID, GROUP_NAME, SOURCE_SYSTEM_ID, TARGET_SYSTEM_ID, SCHEDULE_CRON) 
VALUES (1, 'NIGHTLY_ETL', 
    (SELECT ID FROM SYSTEM_CONFIG WHERE SYSTEM_NAME = 'MYSQL_ERP'),
    (SELECT ID FROM SYSTEM_CONFIG WHERE SYSTEM_NAME = 'ORACLE_DW'),
    '0 0 * * *'
);

INSERT INTO SERVICE_GROUP_CONFIG (ID, GROUP_NAME, SOURCE_SYSTEM_ID, TARGET_SYSTEM_ID, SCHEDULE_CRON) 
VALUES (2, 'REALTIME_STREAMS', 
    (SELECT ID FROM SYSTEM_CONFIG WHERE SYSTEM_NAME = 'LOG_STREAM'),
    (SELECT ID FROM SYSTEM_CONFIG WHERE SYSTEM_NAME = 'ORACLE_DW'),
    '*/5 * * * *'
);

-- Service Details
-- Database to Database
INSERT INTO SERVICE_DETAIL_CONFIG (ID, GROUP_ID, SOURCE_TYPE, SOURCE_DATA_TYPE, EXTRACTION_QUERY, DESTINATION_TABLE, PROCESS_ORDER) 
VALUES (1, 1, 'DATABASE', 'TABLE', 
    'SELECT order_id, customer, amount FROM orders', 'STG_ORDERS', 1);

-- API to Database
INSERT INTO SERVICE_DETAIL_CONFIG (ID, GROUP_ID, SOURCE_TYPE, SOURCE_DATA_TYPE, DESTINATION_TABLE, TARGET_TRUNCATE, PROCESS_ORDER) 
VALUES (2, 1, 'API', 'JSON', 'DIM_CUSTOMERS', 'Y', 2);

-- Kafka to Database
INSERT INTO SERVICE_DETAIL_CONFIG (ID, GROUP_ID, SOURCE_TYPE, SOURCE_DATA_TYPE, DESTINATION_TABLE, TRIM_COL_LIST, PROCESS_ORDER) 
VALUES (3, 2, 'KAFKA', 'CSV', 'SERVER_LOGS', '["hostname", "message"]', 1);

-- Column Mappings
-- Database Column Mapping
INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, DATA_TYPE, PROCESS_ORDER)
VALUES (1, 1, 'order_id', 'ORDER_ID', 'NUMBER', 1);

INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, TRANSFORMATION, PROCESS_ORDER)
VALUES (2, 1, 'customer', 'CUSTOMER_NAME', 'UPPERCASE', 2);

-- API JSON Mapping
INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, DATA_TYPE, PROCESS_ORDER)
VALUES (3, 2, '$.customer.id', 'CUST_ID', 'VARCHAR2(20)', 1);

INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, TRANSFORMATION, PROCESS_ORDER)
VALUES (4, 2, '$.address.city', 'CITY', 'TRIM', 2);

-- Kafka CSV Mapping
INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, DATA_TYPE, PROCESS_ORDER)
VALUES (5, 3, 'timestamp', 'LOG_TS', 'TIMESTAMP', 1);

INSERT INTO SERVICE_COLUMN_MAPPING (ID, SERVICE_DETAIL_ID, SOURCE_PATH, DESTINATION_COLUMN, DATA_TYPE, PROCESS_ORDER)
VALUES (6, 3, 'error_code', 'ERR_CODE', 'NUMBER', 2);

COMMIT;